name: firebase_messaging_handler
description: A comprehensive Flutter plugin for handling Firebase Cloud Messaging notifications with advanced features.
version: 0.0.7
homepage: https://github.com/neel-sharma/firebase_messaging_handler

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: any
  flutter_local_notifications: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: qoder.firebase_messaging_handler
        pluginClass: FirebaseMessagingHandlerPlugin
      ios:
        pluginClass: FirebaseMessagingHandlerPlugin