name: firebase_messaging_handler
description: A comprehensive Flutter plugin for handling Firebase Cloud Messaging notifications with advanced features.
version: 0.0.1
homepage: https://github.com/neel-sharma/firebase_messaging_handler

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  package_info_plus: ^5.0.1
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  platform: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: qoder.firebase_messaging_handler
        pluginClass: FirebaseMessagingHandlerPlugin
      ios:
        pluginClass: FirebaseMessagingHandlerPlugin


