name: firebase_messaging_handler
description: A comprehensive Flutter plugin for handling Firebase Cloud Messaging notifications with advanced features.
version: 0.0.9
homepage: https://github.com/neel-sharma/firebase_messaging_handler

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_messaging: '>=14.6.0'
  flutter_local_notifications: '>=16.0.0'
  shared_preferences: '>=2.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0'
