// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMM9ydmknRKiM6lSp2rx7mTjVrxRvDm2o',
    appId: '1:331316904143:web:048bf1c5a8dc165a84b7ba',
    messagingSenderId: '331316904143',
    projectId: 'notification-utility-example',
    authDomain: 'notification-utility-example.firebaseapp.com',
    storageBucket: 'notification-utility-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAamawTmk7y5hVKbIPx0ktsomgTu16i8vQ',
    appId: '1:331316904143:android:ec819a7ebe30feb384b7ba',
    messagingSenderId: '331316904143',
    projectId: 'notification-utility-example',
    storageBucket: 'notification-utility-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBYn4elHfZQ-ixl8A786U-qoHw1l5rdA',
    appId: '1:331316904143:ios:3b7cdbaac96a83ed84b7ba',
    messagingSenderId: '331316904143',
    projectId: 'notification-utility-example',
    storageBucket: 'notification-utility-example.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBYn4elHfZQ-ixl8A786U-qoHw1l5rdA',
    appId: '1:331316904143:ios:dfb6969d97aeb7f584b7ba',
    messagingSenderId: '331316904143',
    projectId: 'notification-utility-example',
    storageBucket: 'notification-utility-example.appspot.com',
    iosBundleId: 'com.example.example.RunnerTests',
  );
}
